name: optimal_routing
description: Routing game

publish_to: 'none'

version: 1.0.6+9

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: 1.13.1
  firebase_analytics: ^9.1.2

  google_fonts: ^2.3.1
  universal_html: ^2.0.8
  shared_preferences: ^2.0.13
  package_info_plus: ^1.4.0
  lottie: ^1.2.2
  google_mobile_ads: ^1.1.0
  flutter_svg: ^1.0.3
  sentry_flutter: ^6.3.0
  in_app_review: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/
