name: optimal_routing
description: Routing game

publish_to: 'none'

version: 1.0.7+11

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7

  google_fonts: ^3.0.1
  universal_html: ^2.0.8
  shared_preferences: ^2.0.13
  package_info_plus: ^3.0.2
  lottie: ^2.1.0
  google_mobile_ads: ^2.3.0
  flutter_svg: ^1.0.3
  sentry_flutter: ^6.3.0
  in_app_review: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/
